Removes conditional logic for private.yml in create-final-release task
[#114649639

diff --git a/scripts/ci/create-final-release/task b/scripts/ci/create-final-release/task
--- a/scripts/ci/create-final-release/task
+++ b/scripts/ci/create-final-release/task
@@ -1,47 +1,83 @@
 #!/bin/bash -exu
 
-MASTER_BRANCH="${MASTER_BRANCH:-master}"
-
 # Cannot set -u before sourcing .bashrc because of all
 # the unbound variables in things beyond our control.
 set +u
 source ~/.bashrc
 set -u
 
-if [ -n "${PRIVATE_YML_PATH}" ]; then
-  cp "${PRIVATE_YML_PATH}" release-repo/config/
-else
+function main() {
+  local root_dir
+  root_dir="${PWD}"
+
+  local release_name
+  release_name="${1}"
+
+  local master_branch
+  master_branch="${2}"
+
+  configure_bucket "${release_name}"
+  create_and_commit "${root_dir}" "${release_name}" "${master_branch}"
+  copy_to_output "${root_dir}"
+}
+
+function configure_bucket() {
+  local release_name
+  release_name="${1}"
+
   set +x
-  ./mega-ci/scripts/configure_final_release_bucket "${RELEASE_NAME}" ./private-credentials/oss-aws ./release-repo/config
+  ./mega-ci/scripts/configure_final_release_bucket "${release_name}" ./private-credentials/oss-aws ./release-repo/config
   set -x
-fi
+}
 
-pushd release-repo > /dev/null
-  git config user.name "CF MEGA BOT"
-  git config user.email "cf-mega@pivotal.io"
+function create_and_commit() {
+  local root_dir
+  root_dir="${1}"
 
-  git remote add -f master-repo ../release-repo-master
-  git merge "master-repo/${MASTER_BRANCH}" -m 'Merge with master'
+  local release_name
+  release_name="${2}"
 
-  for i in {1..5}; do
-    bosh -n create release --with-tarball --final
-    EXIT_STATUS=${PIPESTATUS[0]}
-    if [ "$EXIT_STATUS" = "0" ]; then
-      break
+  local master_branch
+  master_branch="${3}"
+
+  pushd "${root_dir}/release-repo" > /dev/null
+    git config user.name "CF MEGA BOT"
+    git config user.email "cf-mega@pivotal.io"
+
+    git remote add -f master-repo "${root_dir}/release-repo-master"
+    git merge "master-repo/${master_branch}" -m 'Merge with master'
+
+    local exit_status
+    for i in {1..5}; do
+      bosh -n create release --with-tarball --final
+      exit_status="${PIPESTATUS[0]}"
+
+      if [[ "${exit_status}" == "0" ]]; then
+        break
+      fi
+    done
+
+    if [[ "${exit_status}" != "0" ]]; then
+      echo "Failed to Create ${release_name} Release"
+      exit "${exit_status}"
     fi
-  done
 
-  if [ ! "$EXIT_STATUS" = "0" ]; then
-    echo "Failed to Create $RELEASE_NAME Release"
-    exit "$EXIT_STATUS"
-  fi
+    local new_release_version
+    new_release_version="$(find releases -regex ".*${release_name}-[0-9]*.yml" | egrep -o "${release_name}-[0-9]+" | egrep -o "[0-9]+" | sort -n | tail -n 1)"
 
-  new_release_version=$(find releases -regex ".*${RELEASE_NAME}-[0-9]*.yml" | egrep -o "${RELEASE_NAME}-[0-9]+" | egrep -o "[0-9]+" | sort -n | tail -n 1)
+    git add .final_builds releases
+    git commit -m "Final release ${new_release_version}"
 
-  git add .final_builds releases
-  git commit -m "Final release ${new_release_version}"
-  echo "${new_release_version}" > version_number
-popd > /dev/null
+    echo "${new_release_version}" > version_number
+  popd > /dev/null
+}
 
-shopt -s dotglob
-cp -R release-repo/* final-release-repo
+function copy_to_output() {
+  local root_dir
+  root_dir="${1}"
+
+  shopt -s dotglob
+  cp -R "${root_dir}/release-repo/"* "${root_dir}/final-release-repo"
+}
+
+main "${RELEASE_NAME}" "${MASTER_BRANCH:-"master"}"
