Refactors configure_final_release_bucket script
[#116264073]

Signed-off-by: Kevin Kelani <kkelani@pivotal.io>

diff --git a/scripts/configure_final_release_bucket b/scripts/configure_final_release_bucket
--- a/scripts/configure_final_release_bucket
+++ b/scripts/configure_final_release_bucket
@@ -1,99 +1,180 @@
-#!/bin/bash
+#!/bin/bash -euxf -o pipefail
 
-set -euxf -o pipefail
-
-script_dir="$(cd "$(dirname "$0")" && pwd)"
-
-if [ $# -ne 3 ]; then
-  echo 'Expected 3 argument (release_name path_to_aws_credentials_dir path_to_config_dir) received $#'
-  exit 1
-fi
-release_name=$1
-credentials_dir=$2
-release_config_dir=$3
-
-command -v aws >/dev/null || { echo "aws is required"; exit 1; }
-command -v jq >/dev/null || { echo "jq is required"; exit 1; }
-
-set +x
-  source "${credentials_dir}/aws_environment"
-
-  if [ -z "${AWS_DEFAULT_REGION}" ]; then
-    echo 'AWS_DEFAULT_REGION is not set'
+function validate_arguments() {
+  if [ $# -ne 3 ]; then
+    echo "Expected 3 argument (release_name path_to_aws_credentials_dir path_to_config_dir) received $#"
     exit 1
   fi
+}
 
-  if [ -z "${AWS_ACCESS_KEY_ID}" ]; then
-    echo 'AWS_DEFAULT_REGION is not set'
-    exit 1
-  fi
+function check_dependencies() {
+  command -v aws >/dev/null || { echo "aws is required"; exit 1; }
+  command -v jq >/dev/null || { echo "jq is required"; exit 1; }
+}
 
-  if [ -z "${AWS_SECRET_ACCESS_KEY}" ]; then
-    echo 'AWS_DEFAULT_REGION is not set'
-    exit 1
-  fi
+function load_credentials() {
+  set +x
+    source "${credentials_dir}/aws_environment"
 
-set -x
+    if [[ -z "${AWS_DEFAULT_REGION}" ]]; then
+      echo "AWS_DEFAULT_REGION is not set"
+      exit 1
+    fi
 
-# deploy infrastructure
-if ! aws cloudformation describe-stacks --stack-name "${release_name}-buckets" > /dev/null; then
-  aws cloudformation create-stack \
-    --stack-name "${release_name}-buckets" \
-    --parameters "ParameterKey=BucketName,ParameterValue=${release_name}-release-blobs" \
-    --template-body "file://$script_dir/../templates/final-release/bucket.json" \
-    --capabilities CAPABILITY_IAM > /dev/null
-else
-  aws cloudformation update-stack \
-    --stack-name "${release_name}-buckets" \
-    --parameters "ParameterKey=BucketName,ParameterValue=${release_name}-release-blobs" \
-    --template-body "file://$script_dir/../templates/final-release/bucket.json" \
-    --capabilities CAPABILITY_IAM > /dev/null || true
-fi
+    if [[ -z "${AWS_ACCESS_KEY_ID}" ]]; then
+      echo "AWS_DEFAULT_REGION is not set"
+      exit 1
+    fi
 
-mkdir -p "${credentials_dir}/artifacts/iam-users"
-mkdir -p "${credentials_dir}/artifacts/deployments"
+    if [[ -z "${AWS_SECRET_ACCESS_KEY}" ]]; then
+      echo "AWS_DEFAULT_REGION is not set"
+      exit 1
+    fi
 
-start_time_in_s=$(date +%s)
-wait_time_in_s=$((30 * 60))
-deadline_in_s=$((start_time_in_s + wait_time_in_s))
-while aws cloudformation describe-stacks --stack-name "${release_name}-buckets" | grep StackStatus | grep IN_PROGRESS ; do
-  echo "CloudFormation stack '${release_name}-buckets' still in progress..."
-  current_time_in_s=$(date +%s)
-  remaining_time_in_s=$((deadline_in_s - current_time_in_s))
+  set -x
+}
 
-  if [ "$remaining_time_in_s" -gt 0 ]; then
-    echo "   Waiting ${remaining_time_in_s} more seconds."
-    sleep 15
+function apply_cloudformation_template() {
+  local release_name
+  release_name="${1}"
+
+  local script_dir
+  script_dir="${2}"
+
+  if aws cloudformation describe-stacks --stack-name "${release_name}-buckets" > /dev/null; then
+    apply_stack_operation update "${release_name}" "${script_dir}" || true
   else
-    echo "   Waited ${wait_time_in_s}, aborting."
+    apply_stack_operation create "${release_name}" "${script_dir}"
+  fi
+
+  wait_on_cloudformation "${release_name}"
+  check_final_cloudformation_state "${release_name}"
+}
+
+function apply_stack_operation() {
+  local operation
+  operation="${1}"
+
+  local release_name
+  release_name="${2}"
+
+  local script_dir
+  script_dir="${3}"
+
+  aws cloudformation "${operation}-stack" \
+    --stack-name "${release_name}-buckets" \
+    --parameters "ParameterKey=BucketName,ParameterValue=${release_name}-release-blobs" \
+    --template-body "file://${script_dir}/../templates/final-release/bucket.json" \
+    --capabilities CAPABILITY_IAM > /dev/null
+}
+
+function cloudformation_stack_status() {
+  local release_name
+  release_name="${1}"
+
+  local status
+  status="$(aws cloudformation describe-stacks --stack-name "${release_name}-buckets" | jq -r .Stacks[].StackStatus)"
+
+  printf "%s" "${status}"
+}
+
+function wait_on_cloudformation() {
+  local release_name
+  release_name="${1}"
+
+  local half_an_hour
+  half_an_hour="$((30 * 60))"
+
+  local deadline_in_seconds
+  deadline_in_seconds=$(($(date +%s) + ${half_an_hour}))
+
+  while cloudformation_stack_status "${release_name}" | grep IN_PROGRESS ; do
+    echo "CloudFormation stack '${release_name}-buckets' still in progress..."
+
+    local remaining_time_in_seconds
+    remaining_time_in_seconds="$((deadline_in_seconds - $(date +%s)))"
+
+    if [ "${remaining_time_in_seconds}" -gt 0 ]; then
+      echo "   Waiting ${remaining_time_in_seconds} more seconds."
+      sleep 15
+    else
+      echo "   Waited ${half_an_hour} seconds, aborting."
+      exit 1
+    fi
+  done
+}
+
+function check_final_cloudformation_state() {
+  local release_name
+  release_name="${1}"
+
+  local status
+  status="$(cloudformation_stack_status "${release_name}")"
+
+  if echo "${status}" | grep ROLLBACK ; then
+    echo "CloudFormation failed to apply template: ${status}"
     exit 1
   fi
-done
 
-if aws cloudformation describe-stacks --stack-name "${release_name}-buckets" | grep StackStatus | grep ROLLBACK ; then
-  echo 'Cloud formation failure'
-  exit 1
-fi
+  if ! echo "${status}" | grep COMPLETE ; then
+    echo "CloudFormation failed to apply template: ${status}"
+    exit 1
+  fi
+}
 
-if ! aws cloudformation describe-stacks --stack-name "${release_name}-buckets" | grep StackStatus | grep COMPLETE ; then
-  echo 'Cloud formation failure'
-  exit 1
-fi
+function write_private_yaml() {
+  local release_name
+  release_name="${1}"
 
-aws cloudformation describe-stacks --stack-name "${release_name}-buckets" \
-  > "${credentials_dir}/artifacts/iam-users/${release_name}-buckets.json"
+  local credentials_dir
+  credentials_dir="${2}"
 
-set +x
+  local release_config_dir
+  release_config_dir="${3}"
 
-BLOBS_BUCKET_ACCESS_KEY_ID="$(jq -e -r ".Stacks[0].Outputs[0].OutputValue" "${credentials_dir}/artifacts/iam-users/${release_name}-buckets.json")"
-BLOBS_BUCKET_SECRET_KEY="$(jq -e -r ".Stacks[0].Outputs[1].OutputValue" "${credentials_dir}/artifacts/iam-users/${release_name}-buckets.json")"
+  local bucket_output
+  bucket_output="${credentials_dir}/bucket.json"
 
-set -x
+  aws cloudformation describe-stacks --stack-name "${release_name}-buckets" > "${bucket_output}"
 
-cat > "${release_config_dir}/private.yml" <<EOF
+  local access_key_id
+  local secret_access_key
+
+  set +x
+  access_key_id="$(jq -e -r ".Stacks[0].Outputs[0].OutputValue" "${bucket_output}")"
+  secret_access_key="$(jq -e -r ".Stacks[0].Outputs[1].OutputValue" "${bucket_output}")"
+  set -x
+
+  cat > "${release_config_dir}/private.yml" <<EOF
 ---
 blobstore:
-  s3:
-    secret_access_key: ${BLOBS_BUCKET_SECRET_KEY}
-    access_key_id: ${BLOBS_BUCKET_ACCESS_KEY_ID}
+s3:
+  access_key_id: ${access_key_id}
+  secret_access_key: ${secret_access_key}
 EOF
+
+  rm "${bucket_output}"
+}
+
+function main() {
+  local script_dir
+  script_dir="$(cd "$(dirname "$0")" && pwd)"
+
+  validate_arguments "${@}"
+
+  local release_name
+  release_name="${1}"
+
+  local credentials_dir
+  credentials_dir="${2}"
+
+  local release_config_dir
+  release_config_dir="${3}"
+
+  check_dependencies
+  load_credentials "${credentials_dir}"
+  apply_cloudformation_template "${release_name}" "${script_dir}"
+  write_private_yaml "${release_name}" "${credentials_dir}" "${release_config_dir}"
+}
+
+main "${@}"
