refactor scripts, templates, infrastructure pipeline, and update README

diff --git a/scripts/deploy_bosh b/scripts/deploy_bosh
--- a/scripts/deploy_bosh
+++ b/scripts/deploy_bosh
@@ -1,49 +1,54 @@
 #!/bin/bash
 
+set -e -x
+
 script_dir=$(dirname $0)
 
 if [ $# -ne 1 ]; then
-  echo 'You must provide the path to the bosh secrets stub'
+  echo 'Expected 1 argument (path to deployment directory), received $#'
   exit 1
 fi
+deployment_dir=$1
 
 command -v aws >/dev/null || { echo "aws is required"; exit 1; }
 command -v bosh-init >/dev/null || { echo "bosh-init is required"; exit 1; }
 command -v jq >/dev/null || { echo "jq is required"; exit 1; }
 command -v spiff >/dev/null || { echo "spiff is required"; exit 1; }
 
-if [ -z ${AWS_DEFAULT_REGION} ]; then
-  echo 'AWS_DEFAULT_REGION is not set'
-  exit 1
-fi
+set +x
+  source $deployment_dir/aws_environment
 
-if [ -z ${AWS_ACCESS_KEY_ID} ]; then
-  echo 'AWS_DEFAULT_REGION is not set'
-  exit 1
-fi
+  if [ -z ${AWS_DEFAULT_REGION} ]; then
+    echo 'AWS_DEFAULT_REGION is not set'
+    exit 1
+  fi
 
-if [ -z ${AWS_SECRET_ACCESS_KEY} ]; then
-  echo 'AWS_DEFAULT_REGION is not set'
-  exit 1
-fi
+  if [ -z ${AWS_ACCESS_KEY_ID} ]; then
+    echo 'AWS_DEFAULT_REGION is not set'
+    exit 1
+  fi
 
+  if [ -z ${AWS_SECRET_ACCESS_KEY} ]; then
+    echo 'AWS_DEFAULT_REGION is not set'
+    exit 1
+  fi
 set -x
 
-mkdir -p artifacts/keypair
-mkdir -p artifacts/deployments
+mkdir -p ${deployment_dir}/artifacts/keypair
+mkdir -p ${deployment_dir}/artifacts/deployments
 mkdir -p generated-stubs
 
 # create keypair
 if ! aws ec2 describe-key-pairs --key-names bosh; then
-  aws ec2 create-key-pair --key-name bosh | jq -r .KeyMaterial > artifacts/keypair/id_rsa_bosh
+  aws ec2 create-key-pair --key-name bosh | jq -r .KeyMaterial > ${deployment_dir}/artifacts/keypair/id_rsa_bosh
 fi
 
 # install certs for ELB
 if ! aws iam get-server-certificate --server-certificate-name concourse; then
-  if [ -e certs/concourse_chain.pem ]; then
-    aws iam upload-server-certificate --server-certificate-name concourse --private-key file://certs/concourse.key --certificate-body file://certs/concourse.pem  --certificate-chain file://certs/concourse_chain.pem
+  if [ -e ${deployment_dir}/certs/concourse_chain.pem ]; then
+    aws iam upload-server-certificate --server-certificate-name concourse --private-key file://${deployment_dir}/certs/concourse.key --certificate-body file://${deployment_dir}/certs/concourse.pem  --certificate-chain file://${deployment_dir}/certs/concourse_chain.pem
   else
-    aws iam upload-server-certificate --server-certificate-name concourse --private-key file://certs/concourse.key --certificate-body file://certs/concourse.pem
+    aws iam upload-server-certificate --server-certificate-name concourse --private-key file://${deployment_dir}/certs/concourse.key --certificate-body file://${deployment_dir}/certs/concourse.pem
   fi
 fi
 
@@ -51,46 +56,46 @@ fi
 if ! aws cloudformation describe-stacks | jq -e '.Stacks[0].StackName == "concourse"'; then
   aws cloudformation create-stack \
     --stack-name concourse \
-    --template-body file://$script_dir/../templates/bosh_cloud_formation.json \
+    --template-body file://$script_dir/../templates/cloudformation.json \
     --parameters ParameterKey=LoadBalancerCertName,ParameterValue=concourse
 else
   aws cloudformation update-stack \
     --stack-name concourse \
-    --template-body file://$script_dir/../templates/bosh_cloud_formation.json \
-    --parameters ParameterKey=LoadBalancerCertName,ParameterValue=concourse
+    --template-body file://$script_dir/../templates/cloudformation.json \
+    --parameters ParameterKey=LoadBalancerCertName,ParameterValue=concourse || true # update-stack is not idempotent :(
 fi
 
-aws cloudformation describe-stacks --stack-name mega-test | grep StackStatus | grep IN_PROGRESS
-running=$?
+start_time_in_s=$(date +%s)
+wait_time_in_s=$((30 * 60))
+deadline_in_s=$(($start_time_in_s + $wait_time_in_s))
+while aws cloudformation describe-stacks --stack-name concourse | grep StackStatus | grep IN_PROGRESS ; do
+  echo "CloudFormation stack 'concourse' still in progress..."
+  current_time_in_s=$(date +%s)
+  remaining_time_in_s=$(($deadline_in_s - $current_time_in_s))
 
-while [ ${running} == "0" ]; do
-  sleep 15
-  aws cloudformation describe-stacks --stack-name concourse | grep StackStatus | grep IN_PROGRESS
-  running=$?
+  if [ "$remaining_time_in_s" -gt 0 ]; then
+    echo "   Waiting ${remaining_time_in_s} more seconds."
+    sleep 15
+  else
+    echo "   Waited ${wait_time_in_s}, aborting."
+    exit 1
+  fi
 done
 
-aws cloudformation describe-stacks --stack-name concourse | grep StackStatus | grep "COMPLETE"
-success=$?
-
-if [ ${success} != "0" ]; then
+if ! aws cloudformation describe-stacks --stack-name concourse | grep StackStatus | grep COMPLETE ; then
   echo 'Cloud formation failure'
   exit 1
 fi
-
-set -e
 
 # generate AWS resources stub for shared purposes
 aws cloudformation describe-stack-resources --stack-name concourse \
   | jq '.StackResources|map({key: .LogicalResourceId, value: .PhysicalResourceId}) | from_entries as $body | {Resources: $body}' \
   > generated-stubs/aws-resources.json
 
-BOSH_SUBNET_ID=$(cat generated-stubs/aws-resources.json | jq -r .Resources.BOSHSubnet)
-AWS_ZONE=$(aws ec2 describe-subnets --subnet-ids $BOSH_SUBNET_ID | jq -r .Subnets[0].AvailabilityZone)
-
+# generate stub for BOSH Security Group Name
 BOSH_SECURITY_GROUP_ID=$(cat generated-stubs/aws-resources.json | jq -r .Resources.BOSHSecurityGroup)
 BOSH_SECURITY_GROUP_NAME=$(aws ec2 describe-security-groups --group-ids ${BOSH_SECURITY_GROUP_ID} | jq -r .SecurityGroups[0].GroupName)
 
-# generate stub for BOSH Security Group Name
 cat > generated-stubs/security-groups.yml <<EOF
 {
   "SecurityGroups": {
@@ -100,6 +105,9 @@ cat > generated-stubs/security-groups.yml <<EOF
 EOF
 
 # generate stub for AWS Credentials
+BOSH_SUBNET_ID=$(cat generated-stubs/aws-resources.json | jq -r .Resources.BOSHSubnet)
+AWS_ZONE=$(aws ec2 describe-subnets --subnet-ids $BOSH_SUBNET_ID | jq -r .Subnets[0].AvailabilityZone)
+
 cat > generated-stubs/aws-credentials.yml <<EOF
 {
   "AWSCredentials": {
@@ -111,21 +119,22 @@ cat > generated-stubs/aws-credentials.yml <<EOF
 }
 EOF
 
-# generate bosh deployment manifest
+# generate BOSH deployment manifest
+echo "# GENERATED: NO TOUCHING" > ${deployment_dir}/artifacts/deployments/bosh.yml
 spiff merge $script_dir/../templates/bosh.yml \
   generated-stubs/aws-credentials.yml \
   generated-stubs/aws-resources.json \
   generated-stubs/security-groups.yml \
-  "$1" \
-  > artifacts/deployments/bosh.yml
+  ${deployment_dir}/stubs/bosh/bosh_passwords.yml \
+  >> ${deployment_dir}/artifacts/deployments/bosh.yml
 
-bosh-init deploy  artifacts/deployments/bosh.yml
+# deploy BOSH
+bosh-init deploy ${deployment_dir}/artifacts/deployments/bosh.yml
 
-# Target bosh
+# display result
 BOSH_IP=$(cat generated-stubs/aws-resources.json | jq -r .Resources.MicroEIP)
-bosh -n target $BOSH_IP
-bosh login admin admin
+echo "BOSH director is at $BOSH_IP"
 
+# clean up
 rm -rf generated-stubs
 
-echo "BOSH director is at $BOSH_IP, username: admin, password: admin"
diff --git a/scripts/deploy_concourse b/scripts/deploy_concourse
--- a/scripts/deploy_concourse
+++ b/scripts/deploy_concourse
@@ -1,99 +1,118 @@
 #!/bin/bash
 
-set -ex
+set -e -x
 
 script_dir=$(dirname $0)
 
-STUB_PATH=$1
-
-if [ -z ${STUB_PATH} ]; then
-  echo 'Usage: deploy_concourse STUB_FILE'
+if [ $# -ne 1 ]; then
+  echo 'Expected 1 argument (path to deployment directory), received $#'
   exit 1
 fi
+deployment_dir=$1
 
-if [ -z ${AWS_DEFAULT_REGION} ]; then
-  echo 'AWS_DEFAULT_REGION is not set'
-  exit 1
-fi
+command -v aws >/dev/null || { echo "aws is required"; exit 1; }
+command -v bosh >/dev/null || { echo "bosh is required"; exit 1; }
+command -v jq >/dev/null || { echo "jq is required"; exit 1; }
+command -v spiff >/dev/null || { echo "spiff is required"; exit 1; }
 
-if [ -z ${AWS_ACCESS_KEY_ID} ]; then
-  echo 'AWS_DEFAULT_REGION is not set'
-  exit 1
-fi
+set +x
+  source ${deployment_dir}/aws_environment
 
-if [ -z ${AWS_SECRET_ACCESS_KEY} ]; then
-  echo 'AWS_DEFAULT_REGION is not set'
-  exit 1
-fi
+  if [ -z ${AWS_DEFAULT_REGION} ]; then
+    echo 'AWS_DEFAULT_REGION is not set'
+    exit 1
+  fi
 
-STEMCELL_PATH=$(cat $STUB_PATH | jq -r .stemcell)
-CONCOURSE_RELEASE_PATH=$(cat $STUB_PATH | jq -r .concourse_release)
-GARDEN_RELEASE_PATH=$(cat $STUB_PATH | jq -r .garden_release)
+  if [ -z ${AWS_ACCESS_KEY_ID} ]; then
+    echo 'AWS_DEFAULT_REGION is not set'
+    exit 1
+  fi
 
-mkdir -p artifacts/deployments
-mkdir -p generated-stubs/concourse
+  if [ -z ${AWS_SECRET_ACCESS_KEY} ]; then
+    echo 'AWS_DEFAULT_REGION is not set'
+    exit 1
+  fi
+
+  source ${deployment_dir}/bosh_environment
+
+  if [ -z ${BOSH_USER} ]; then
+    echo 'BOSH_USER is not set'
+    exit 1
+  fi
+
+  if [ -z ${BOSH_PASSWORD} ]; then
+    echo 'BOSH_PASSWORD is not set'
+    exit 1
+  fi
+
+  if [ -z ${BOSH_DIRECTOR} ]; then
+    echo 'BOSH_DIRECTOR is not set'
+    exit 1
+  fi
+set -x
+
+mkdir -p ${deployment_dir}/artifacts/deployments
+mkdir -p generated-stubs
+
+# Target bosh
+bosh -n target $BOSH_DIRECTOR
+set +x
+  bosh login $BOSH_USER $BOSH_PASSWORD
+set -x
+
+# Obtain bosh uuid for manifest generation
+BOSH_UUID=$(bosh --no-color status --uuid)
+cat > generated-stubs/director_uuid.yml <<EOF
+---
+director_uuid: $BOSH_UUID
+EOF
 
 # generate AWS resources stub for shared purposes
 aws cloudformation describe-stack-resources --stack-name concourse \
   | jq '.StackResources|map({key: .LogicalResourceId, value: .PhysicalResourceId}) | from_entries as $body | {Resources: $body}' \
   > generated-stubs/aws-resources.json
 
-# Target bosh
-BOSH_IP=$(cat generated-stubs/aws-resources.json | jq -r .Resources.MicroEIP)
-bosh -n target $BOSH_IP
-
-# Obtain bosh uuid for manifest generation
-BOSH_UUID=$(bosh --no-color status --uuid)
-cat > generated-stubs/concourse/uuid_stub.yml <<EOF
----
-director_uuid: $BOSH_UUID
-EOF
-
-# Generate the network for concourse
-# Note: this network range should be associated with the Resources.InternalSubnet property
+# Generate the cloud propeties stub
 SUBNET_ID=$(cat generated-stubs/aws-resources.json | jq -r .Resources.InternalSubnet)
-LOAD_BALANCER=$(cat generated-stubs/aws-resources.json | jq -r .Resources.WebELBLoadBalancer)
+
 INTERNAL_SECURITY_GROUP_ID=$(cat generated-stubs/aws-resources.json | jq -r .Resources.InternalSecurityGroup)
 INTERNAL_SECURITY_GROUP_NAME=$(aws ec2 describe-security-groups --group-ids ${INTERNAL_SECURITY_GROUP_ID} | jq .SecurityGroups[0].GroupName)
-cat > generated-stubs/concourse/networks_stub.yml <<EOF
----
-networks:
-  - name: concourse
-    type: manual
-    subnets:
-      - range: 10.0.16.0/20
-        reserved: [10.0.16.2 - 10.0.16.9]
-        static: [10.0.16.31]
-        dns: [10.0.0.2]
-        gateway: 10.0.16.1
-        cloud_properties:
-          security_groups: [$INTERNAL_SECURITY_GROUP_NAME]
-          subnet: $SUBNET_ID
-EOF
 
-# Grab availability zone
-AWS_ZONE=$(cat generated-stubs/aws-credentials  .yml | jq -r .AWSCredentials.AWS_ZONE)
-cat > generated-stubs/concourse/aws_config_stub.yml <<EOF
+AWS_ZONE=$(aws ec2 describe-subnets --subnet-ids $SUBNET_ID | jq -r .Subnets[0].AvailabilityZone)
+
+LOAD_BALANCER=$(cat generated-stubs/aws-resources.json | jq -r .Resources.WebELBLoadBalancer)
+
+cat > generated-stubs/cloud_properties.yml <<EOF
 ---
-aws_config:
+cloud_properties:
+  security_group_name: $INTERNAL_SECURITY_GROUP_NAME
+  subnet_id: $SUBNET_ID
   az: $AWS_ZONE
   load_balancer: $LOAD_BALANCER
 EOF
 
+# Generate Concourse manifest
+echo "# GENERATED, NO TOUCHING" > ${deployment_dir}/artifacts/deployments/concourse.yml
 spiff merge $script_dir/../templates/concourse.yml \
-  generated-stubs/concourse/aws_config_stub.yml \
-  generated-stubs/concourse/networks_stub.yml \
-  generated-stubs/concourse/uuid_stub.yml \
-  $script_dir/../templates/secrets_stub.yml \
-  "$1" > artifacts/deployments/concourse.yml
+  generated-stubs/director_uuid.yml \
+  generated-stubs/cloud_properties.yml \
+  ${deployment_dir}/stubs/concourse/atc_credentials.yml \
+  >> ${deployment_dir}/artifacts/deployments/concourse.yml
 
-bosh -n deployment artifacts/deployments/concourse.yml
+# Upload binaries to BOSH director
+STEMCELL_PATH=$(cat $deployment_dir/stubs/concourse/binary_urls.json | jq -r .stemcell)
+CONCOURSE_RELEASE_PATH=$(cat $deployment_dir/stubs/concourse/binary_urls.json | jq -r .concourse_release)
+GARDEN_RELEASE_PATH=$(cat $deployment_dir/stubs/concourse/binary_urls.json | jq -r .garden_release)
 bosh -n upload stemcell $STEMCELL_PATH --skip-if-exists
 bosh -n upload release $CONCOURSE_RELEASE_PATH --skip-if-exists
 bosh -n upload release $GARDEN_RELEASE_PATH --skip-if-exists
-bosh -n deploy
 
-rm -rf generated-stubs
+# Deploy Concourse
+bosh -n -d ${deployment_dir}/artifacts/deployments/concourse.yml deploy
 
+# display result
 LOAD_BALANCER_DNSName=$(aws elb describe-load-balancers --load-balancer-names $LOAD_BALANCER| jq -r .LoadBalancerDescriptions[0].DNSName)
 echo "Concourse available at https://$LOAD_BALANCER_DNSName"
+
+# clean up
+rm -rf generated-stubs
