Pull out db parameters for use in cf stub
[#100380270]

Signed-off-by: Natalie J. Bennett <nbennett@pivotal.io>

diff --git a/scripts/deploy_cf_bosh_instance b/scripts/deploy_cf_bosh_instance
--- a/scripts/deploy_cf_bosh_instance
+++ b/scripts/deploy_cf_bosh_instance
@@ -1,5 +1,66 @@
 #!/bin/bash
 
+deploy_buckets() {
+  if ! aws cloudformation describe-stacks --stack-name cf-deployment-buckets; then
+    aws cloudformation create-stack \
+      --stack-name cf-deployment-buckets \
+      --template-body file://$script_dir/../templates/cf-deployment/buckets.json \
+      --parameters file://${deployment_dir}/cloud_formation/buckets-properties.json \
+      --capabilities CAPABILITY_IAM
+  else
+    aws cloudformation update-stack \
+      --stack-name cf-deployment-buckets \
+      --template-body file://$script_dir/../templates/cf-deployment/buckets.json \
+      --parameters file://${deployment_dir}/cloud_formation/buckets-properties.json \
+      --capabilities CAPABILITY_IAM || true
+  fi
+
+  wait_for_deployment cf-deployment-buckets
+
+  mkdir -p ${deployment_dir}/artifacts/iam-users
+
+  aws cloudformation describe-stacks --stack-name cf-deployment-buckets \
+      > ${deployment_dir}/artifacts/iam-users/etcd-buckets.json
+}
+
+deploy_bosh_and_cf() {
+  # deploy infrastructure
+  if ! aws cloudformation describe-stacks --stack-name cf-deployment ; then
+    aws cloudformation create-stack \
+      --stack-name cf-deployment \
+      --template-body file://$script_dir/../templates/cf-deployment/cloudformation.json \
+      --parameters file://${deployment_dir}/cloud_formation/properties.json
+  else
+    aws cloudformation update-stack \
+      --stack-name cf-deployment \
+      --template-body file://$script_dir/../templates/cf-deployment/cloudformation.json \
+      --parameters file://${deployment_dir}/cloud_formation/properties.json || true # update-stack is not idempotent :(
+  fi
+
+  wait_for_deployment cf-deployment
+}
+
+wait_for_deployment() {
+  DEPLOYMENT_NAME=$1
+
+  start_time_in_s=$(date +%s)
+  wait_time_in_s=$((30 * 60))
+  deadline_in_s=$(($start_time_in_s + $wait_time_in_s))
+  while aws cloudformation describe-stacks --stack-name $DEPLOYMENT_NAME | grep StackStatus | grep IN_PROGRESS ; do
+    echo "CloudFormation stack 'cf-deployment' still in progress..."
+    current_time_in_s=$(date +%s)
+    remaining_time_in_s=$(($deadline_in_s - $current_time_in_s))
+
+    if [ "$remaining_time_in_s" -gt 0 ]; then
+      echo "   Waiting ${remaining_time_in_s} more seconds."
+      sleep 15
+    else
+      echo "   Waited ${wait_time_in_s}, aborting."
+      exit 1
+    fi
+  done
+}
+
 set -e -x
 
 script_dir=$(dirname $0)
@@ -50,35 +111,9 @@ if ! aws iam get-server-certificate --server-certificate-name cf; then
   aws iam upload-server-certificate --server-certificate-name cf --private-key file://${deployment_dir}/certs/cf.key --certificate-body file://${deployment_dir}/certs/cf.pem
 fi
 
-# deploy infrastructure
-if ! aws cloudformation describe-stacks --stack-name cf-deployment ; then
-  aws cloudformation create-stack \
-    --stack-name cf-deployment \
-    --template-body file://$script_dir/../templates/cf-deployment/cloudformation.json \
-    --parameters file://${deployment_dir}/cloud_formation/properties.json
-else
-  aws cloudformation update-stack \
-    --stack-name cf-deployment \
-    --template-body file://$script_dir/../templates/cf-deployment/cloudformation.json \
-    --parameters file://${deployment_dir}/cloud_formation/properties.json || true # update-stack is not idempotent :(
-fi
-
-start_time_in_s=$(date +%s)
-wait_time_in_s=$((30 * 60))
-deadline_in_s=$(($start_time_in_s + $wait_time_in_s))
-while aws cloudformation describe-stacks --stack-name cf-deployment | grep StackStatus | grep IN_PROGRESS ; do
-  echo "CloudFormation stack 'cf-deployment' still in progress..."
-  current_time_in_s=$(date +%s)
-  remaining_time_in_s=$(($deadline_in_s - $current_time_in_s))
-
-  if [ "$remaining_time_in_s" -gt 0 ]; then
-    echo "   Waiting ${remaining_time_in_s} more seconds."
-    sleep 15
-  else
-    echo "   Waited ${wait_time_in_s}, aborting."
-    exit 1
-  fi
-done
+# deploy cloud formation templates
+deploy_bosh_and_cf
+deploy_buckets
 
 if aws cloudformation describe-stacks --stack-name cf-deployment | grep StackStatus | grep ROLLBACK ; then
   echo 'Cloud formation failure'
@@ -123,8 +158,10 @@ cat > generated-stubs/${cf_deployment_name}/aws-credentials.yml <<EOF
 EOF
 
 # generate CF Resources Stub
-CF_Subnet=$(cat generated-stubs/${cf_deployment_name}/aws-resources.json | jq -r .Resources.CFSubnet)
-CF_AWS_ZONE=$(aws ec2 describe-subnets --subnet-ids $CF_Subnet | jq -r .Subnets[0].AvailabilityZone)
+CF_Subnet_1=$(cat generated-stubs/${cf_deployment_name}/aws-resources.json | jq -r .Resources.CFSubnetAZ1)
+CF_AWS_ZONE_1=$(aws ec2 describe-subnets --subnet-ids $CF_Subnet_1 | jq -r .Subnets[0].AvailabilityZone)
+CF_Subnet_2=$(cat generated-stubs/${cf_deployment_name}/aws-resources.json | jq -r .Resources.CFSubnetAZ2)
+CF_AWS_ZONE_2=$(aws ec2 describe-subnets --subnet-ids $CF_Subnet_2 | jq -r .Subnets[0].AvailabilityZone)
 CF_ELB=$(cat generated-stubs/${cf_deployment_name}/aws-resources.json | jq -r .Resources.CFLoadBalancer)
 CF_SECURITY_GROUP_ID=$(cat generated-stubs/${cf_deployment_name}/aws-resources.json | jq -r .Resources.CFSecurityGroup)
 CF_SECURITY_GROUP_NAME=$(aws ec2 describe-security-groups --group-ids ${CF_SECURITY_GROUP_ID} | jq -r .SecurityGroups[0].GroupName)
@@ -132,10 +169,39 @@ CF_SECURITY_GROUP_NAME=$(aws ec2 describe-security-groups --group-ids ${CF_SECUR
 cat > ${deployment_dir}/generated-stubs/cf/cf-resources.yml<<EOF
 ---
 cf_resources:
-  availability_zone: $CF_AWS_ZONE
+  subnets:
+    - subnet_id: $CF_Subnet_1
+      availability_zone: $CF_AWS_ZONE_1
+    - subnet_id: $CF_Subnet_2
+      availability_zone: $CF_AWS_ZONE_2
   elb: $CF_ELB
   security_group_name: $CF_SECURITY_GROUP_NAME
-  subnet_id: $CF_Subnet
+EOF
+
+cat ${deployment_dir}/cloud_formation/properties.json | \
+  jq '.|map({key: .ParameterKey, value: .ParameterValue}) | from_entries as $body | {cloud_formation_inputs: $body}' \
+  > ${deployment_dir}/generated-stubs/cf/cf-cloud-formation-inputs.json
+
+# generate CF database stub
+CCDB=$(cat generated-stubs/${cf_deployment_name}/aws-resources.json | jq -r .Resources.CCDB)
+UAADB=$(cat generated-stubs/${cf_deployment_name}/aws-resources.json | jq -r .Resources.UAADB)
+CCDB_INFO=$(aws rds describe-db-instances --db-instance-identifier ccdb)
+CCDB_HOST=$(echo $CCDB_INFO | jq -r '.DBInstances[0].Endpoint.Address')
+CCDB_PORT=$(echo $CCDB_INFO | jq -r '.DBInstances[0].Endpoint.Port')
+
+UAADB_INFO=$(aws rds describe-db-instances --db-instance-identifier uaadb)
+UAADB_HOST=$(echo $UAADB_INFO | jq -r '.DBInstances[0].Endpoint.Address')
+UAADB_PORT=$(echo $UAADB_INFO | jq -r '.DBInstances[0].Endpoint.Port')
+
+cat > ${deployment_dir}/generated-stubs/cf/cf-databases.yml<<EOF
+---
+cf_databases:
+  ccdb_database: $CCDB
+  ccdb_host: $CCDB_HOST
+  ccdb_port: $CCDB_PORT
+  uaadb_database: $UAADB
+  uaadb_host: $UAADB_HOST
+  uaadb_port: $UAADB_PORT
 EOF
 
 # generate BOSH deployment manifest
@@ -164,4 +230,3 @@ EOF
 
 # clean up
 rm -rf generated-stubs
-
