generate a dev release from blessed git sha and finalize the release
* This allows us to not require 'bosh sync blobs'

[#100380306]

Signed-off-by: Dies Köper <diesk@fast.au.fujitsu.com>

diff --git a/scripts/ci/etcd/create-final-release b/scripts/ci/etcd/create-final-release
--- a/scripts/ci/etcd/create-final-release
+++ b/scripts/ci/etcd/create-final-release
@@ -6,8 +6,7 @@ source ~/.bashrc
 cd $ETCD_RELEASE_DIR
 
 for i in {1..5}; do
-  echo "Creating release, attempt $i"
-  bosh -n create release --with-tarball --final
+  bosh -n create release --with-tarball
   EXIT_STATUS=${PIPESTATUS[0]}
   if [ "$EXIT_STATUS" = "0" ]; then
     break
@@ -19,4 +18,18 @@ if [ ! "$EXIT_STATUS" = "0" ]; then
   exit $EXIT_STATUS
 fi
 
+dev_release=$(ls dev_releases/etcd/ | grep .tgz)
 
+for i in {1..5}; do
+  echo "Creating release, attempt $i"
+  bosh -n finalize release dev_releases/etcd/$dev_release
+  EXIT_STATUS=${PIPESTATUS[0]}
+  if [ "$EXIT_STATUS" = "0" ]; then
+    break
+  fi
+done
+
+if [ ! "$EXIT_STATUS" = "0" ]; then
+  echo "Failed to Create ETCD Release"
+  exit $EXIT_STATUS
+fi
